### ISSUE TITLE
Dfinity grant application resubmit

### ISSUE THREAD

**Issue by edwardoranj** [oranj-base/strike#18]
## TODOS

- [ ] Write high-level and low-level architecture diagram, user journey
- [ ] Write user story / milestone
- [ ] whilte list registry canister
- [ ] betBTC & STRIKE

- Be as specific as possible and include user stories in your milestones to give a clear picture of the scope of your work (how will canister devs utlize STRIKE and create actions, how does the StrikeRegistry work and how is whitelisting of canisters handled, what's the flow for devs/users, ...)
- Provide an architecture overview for the solution you are building (should be provided before a grant proposal is submitted)
- Avoid including non-technical milestones (marketing, strategy, onboarding users...)
